#pragma once
#include "CoreMinimal.h"
#include "AetherAITypes.generated.h"
UENUM(BlueprintType) enum class EAetherAIRequestType:uint8{Dialogue,NPCDecision,LoreGeneration,GMExplanation};
UENUM(BlueprintType) enum class EAetherAIResult:uint8{Accepted,InvalidConfiguration,InvalidRequest,NotAuthenticated,RateLimited,ContextTooLarge,ProviderUnavailable,ProviderRejected,UnsafeOutput,InvalidToolProposal};
UENUM(BlueprintType) enum class EAetherAIToolAction:uint8{None,OfferQuest,OpenShop,StartDialogue,MarkInterestPoint};
USTRUCT(BlueprintType) struct FAetherAIConfig{GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadOnly) bool bEnabled=true; UPROPERTY(EditAnywhere,BlueprintReadOnly) int32 MaxRequestsPerMinute=20; UPROPERTY(EditAnywhere,BlueprintReadOnly) int32 MaxContextCharacters=12000; UPROPERTY(EditAnywhere,BlueprintReadOnly) int32 MaxOutputCharacters=4000; UPROPERTY(EditAnywhere,BlueprintReadOnly) int32 MaxMemoryEntries=20; UPROPERTY(EditAnywhere,BlueprintReadOnly) float Temperature=.2f; UPROPERTY(EditAnywhere,BlueprintReadOnly) bool bAllowToolProposals=true; bool IsValid()const{return MaxRequestsPerMinute>0&&MaxContextCharacters>=256&&MaxOutputCharacters>=128&&MaxMemoryEntries>=0&&Temperature>=0.f&&Temperature<=2.f;}};
USTRUCT(BlueprintType) struct FAetherAIMemoryEntry{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) FString Key; UPROPERTY(BlueprintReadOnly) FString Value; UPROPERTY(BlueprintReadOnly) double CreatedAt=0.;};
USTRUCT(BlueprintType) struct FAetherAIContext{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) FString AccountId; UPROPERTY(BlueprintReadOnly) FString CharacterId; UPROPERTY(BlueprintReadOnly) FString CharacterName; UPROPERTY(BlueprintReadOnly) FString Locale; UPROPERTY(BlueprintReadOnly) FString SystemContext; UPROPERTY(BlueprintReadOnly) FString PlayerInput; UPROPERTY(BlueprintReadOnly) TArray<FAetherAIMemoryEntry> Memory; int32 ApproximateCharacterCount()const{int32 T=AccountId.Len()+CharacterId.Len()+CharacterName.Len()+Locale.Len()+SystemContext.Len()+PlayerInput.Len();for(const auto&E:Memory)T+=E.Key.Len()+E.Value.Len();return T;}};
USTRUCT(BlueprintType) struct FAetherAIToolProposal{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) EAetherAIToolAction Action=EAetherAIToolAction::None; UPROPERTY(BlueprintReadOnly) FString TargetId; UPROPERTY(BlueprintReadOnly) FString Reason;};
USTRUCT(BlueprintType) struct FAetherAIResponse{GENERATED_BODY() UPROPERTY(BlueprintReadOnly) EAetherAIResult Result=EAetherAIResult::ProviderUnavailable; UPROPERTY(BlueprintReadOnly) FString Text; UPROPERTY(BlueprintReadOnly) TArray<FAetherAIToolProposal> ToolProposals; UPROPERTY() uint64 RequestId=0;};
USTRUCT(BlueprintType) struct FAetherAIRequest{GENERATED_BODY() UPROPERTY() uint64 RequestId=0; UPROPERTY(BlueprintReadOnly) EAetherAIRequestType Type=EAetherAIRequestType::Dialogue; UPROPERTY(BlueprintReadOnly) FAetherAIContext Context;};
