#include "Misc/AutomationTest.h"
#include "Production/AetherProductionService.h"
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherProductionConfigTest,"AgeOfAether.Production.Config",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherProductionConfigTest::RunTest(const FString&){FAetherProductionConfig C;TestTrue(TEXT("Valid"),C.IsValid());C.MaxAuditEvents=1;TestFalse(TEXT("Audit minimum"),C.IsValid());return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherProductionHealthTest,"AgeOfAether.Production.Health",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherProductionHealthTest::RunTest(const FString&){FAetherProductionService S;TestTrue(TEXT("Initialize"),S.Initialize(FAetherProductionConfig(),10.));auto H=S.GetHealth(10.);TestTrue(TEXT("Liveness"),H.bLiveness);TestFalse(TEXT("Not ready"),H.bReadiness);for(uint8 I=0;I<=static_cast<uint8>(EAetherProductionCheck::Content);++I)S.SetCheck(static_cast<EAetherProductionCheck>(I),true);H=S.GetHealth(11.);TestTrue(TEXT("Ready"),H.bReadiness);TestEqual(TEXT("State"),H.State,EAetherProductionState::Ready);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherProductionDrainTest,"AgeOfAether.Production.Drain",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherProductionDrainTest::RunTest(const FString&){FAetherProductionService S;S.Initialize(FAetherProductionConfig(),0.);S.BeginDrain(5.);auto H=S.GetHealth(5.);TestEqual(TEXT("Draining"),H.State,EAetherProductionState::Draining);TestTrue(TEXT("Live during drain"),H.bLiveness);TestFalse(TEXT("Not ready"),H.bReadiness);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherProductionBoundsTest,"AgeOfAether.Production.Bounds",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherProductionBoundsTest::RunTest(const FString&){FAetherProductionService S;FAetherProductionConfig C;C.MaxAuditEvents=100;S.Initialize(C,0.);for(int32 I=0;I<101;++I){S.RecordMetric(TEXT("tick"),I,I);S.RecordEvent(TEXT("event"),TEXT("x"),false,I);}TestEqual(TEXT("Metric bounded"),S.GetMetrics().Num(),100);TestEqual(TEXT("Event bounded"),S.GetEvents().Num(),100);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherProductionFailureTest,"AgeOfAether.Production.Failure",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherProductionFailureTest::RunTest(const FString&){FAetherProductionService S;FAetherProductionConfig C;C.BuildVersion.Empty();TestFalse(TEXT("Invalid config"),S.Initialize(C,0.));TestFalse(TEXT("Metric rejects NaN"),S.RecordMetric(TEXT("x"),TNumericLimits<double>::QuietNaN(),0.),false);return true;}
