#include "Misc/AutomationTest.h"
#include "Data/AetherSkillEffectRegistry.h"
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherSkillEffectBasicTest,"AgeOfAether.Data.SkillEffect.Basic",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FAetherSkillEffectBasicTest::RunTest(const FString&){FAetherSkillEffectRegistry R;FString E;FAetherEffectDefinition F;F.DefinitionID=TEXT("Effect.Burn");F.DisplayName=TEXT("Burn");F.Type=EAetherEffectType::DamageOverTime;F.DurationSeconds=5;F.TickIntervalSeconds=1;F.Magnitude=10;TestTrue(TEXT("effect"),R.RegisterEffect(F,E));FAetherDataSkillDefinition S;S.DefinitionID=TEXT("Skill.Fire");S.DisplayName=TEXT("Fire");S.EffectIDs.Add(TEXT("Effect.Burn"));TestTrue(TEXT("skill"),R.RegisterSkill(S,E));FAetherStatusDefinition T;T.DefinitionID=TEXT("Status.Burning");T.DisplayName=TEXT("Burning");T.EffectIDs.Add(TEXT("Effect.Burn"));TestTrue(TEXT("status"),R.RegisterStatus(T,E));TestEqual(TEXT("count"),R.NumSkills()+R.NumEffects()+R.NumStatuses(),3);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherSkillEffectValidationTest,"AgeOfAether.Data.SkillEffect.Validation",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FAetherSkillEffectValidationTest::RunTest(const FString&){FAetherSkillEffectRegistry R;FString E;FAetherDataSkillDefinition S;S.DefinitionID=TEXT("Skill.Bad");S.DisplayName=TEXT("Bad");S.RequiredLevel=0;TestFalse(TEXT("bad level"),R.RegisterSkill(S,E));FAetherEffectDefinition F;F.DefinitionID=TEXT("Effect.Bad");F.DisplayName=TEXT("Bad");F.DurationSeconds=0;F.TickIntervalSeconds=1;TestFalse(TEXT("tick needs duration"),R.RegisterEffect(F,E));FAetherStatusDefinition T;T.DefinitionID=TEXT("Status.Bad");T.DisplayName=TEXT("Bad");TestFalse(TEXT("status needs effect"),R.RegisterStatus(T,E));return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherSkillEffectCrossReferenceTest,"AgeOfAether.Data.SkillEffect.CrossReferences",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FAetherSkillEffectCrossReferenceTest::RunTest(const FString&){FAetherSkillEffectRegistry R;FString E;FAetherDataSkillDefinition S;S.DefinitionID=TEXT("Skill.Missing");S.DisplayName=TEXT("Missing");S.EffectIDs.Add(TEXT("Effect.Nope"));TestTrue(TEXT("structural register"),R.RegisterSkill(S,E));TArray<FAetherSkillEffectValidationIssue>I;TestFalse(TEXT("missing effect detected"),R.Validate(I));TestTrue(TEXT("issue"),I.ContainsByPredicate([](const FAetherSkillEffectValidationIssue&X){return X.Code==TEXT("MissingEffectReference");}));return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherSkillEffectDuplicateTest,"AgeOfAether.Data.SkillEffect.Duplicate",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FAetherSkillEffectDuplicateTest::RunTest(const FString&){FAetherSkillEffectRegistry R;FString E;FAetherEffectDefinition F;F.DefinitionID=TEXT("Shared.ID");F.DisplayName=TEXT("A");TestTrue(TEXT("first"),R.RegisterEffect(F,E));FAetherDataSkillDefinition S;S.DefinitionID=TEXT("Shared.ID");S.DisplayName=TEXT("B");TestFalse(TEXT("cross-type duplicate"),R.RegisterSkill(S,E));return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherSkillEffectDeterminismTest,"AgeOfAether.Data.SkillEffect.Determinism",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FAetherSkillEffectDeterminismTest::RunTest(const FString&){FAetherSkillEffectRegistry R;FString E;FAetherEffectDefinition F;F.DisplayName=TEXT("F");F.DefinitionID=TEXT("Effect.Z");R.RegisterEffect(F,E);F.DefinitionID=TEXT("Effect.A");R.RegisterEffect(F,E);FAetherDataSkillDefinition S;S.DisplayName=TEXT("S");S.DefinitionID=TEXT("Skill.M");R.RegisterSkill(S,E);TArray<FString>I;R.GetDefinitionIDs(I);TestEqual(TEXT("0"),I[0],FString(TEXT("Effect.A")));TestEqual(TEXT("1"),I[1],FString(TEXT("Effect.Z")));TestEqual(TEXT("2"),I[2],FString(TEXT("Skill.M")));return true;}
