#include "Misc/AutomationTest.h"
#include "AI/AetherAIService.h"
class FAetherAITestProvider final:public IAetherAIProvider{public:bool bShouldSucceed=true;bool bReturnUnsafeOutput=false;bool bReturnInvalidTool=false;FString LastCharacterId;int32 CallCount=0;bool Generate(const FAetherAIRequest&R,const FAetherAIConfig&,FAetherAIResponse&O)override{++CallCount;LastCharacterId=R.Context.CharacterId;if(!bShouldSucceed)return false;O.Text=bReturnUnsafeOutput?TEXT("API_KEY=secret"):TEXT("Aether response");if(bReturnInvalidTool){FAetherAIToolProposal P;P.Action=EAetherAIToolAction::None;P.TargetId=TEXT("quest-1");O.ToolProposals.Add(P);}return true;}};
static FAetherAIRequest Req(uint64 Id,const TCHAR*Account=TEXT("account")){FAetherAIRequest R;R.RequestId=Id;R.Context.AccountId=Account;R.Context.CharacterId=TEXT("character");R.Context.PlayerInput=TEXT("Hello");return R;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIConfigTest,"AgeOfAether.AI.Config",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIConfigTest::RunTest(const FString&){FAetherAIConfig C;TestTrue(TEXT("Default valid"),C.IsValid());C.MaxContextCharacters=0;TestFalse(TEXT("Invalid context"),C.IsValid());return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIRequestTest,"AgeOfAether.AI.Request",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIRequestTest::RunTest(const FString&){auto P=MakeShared<FAetherAITestProvider>();FAetherAIService S;TestTrue(TEXT("Init"),S.Initialize(FAetherAIConfig(),P));FAetherAIResponse O;TestEqual(TEXT("Accepted"),S.SubmitRequest(Req(1),1.,O),EAetherAIResult::Accepted);TestEqual(TEXT("Provider called"),P->CallCount,1);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIReplayTest,"AgeOfAether.AI.Replay",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIReplayTest::RunTest(const FString&){auto P=MakeShared<FAetherAITestProvider>();FAetherAIService S;S.Initialize(FAetherAIConfig(),P);FAetherAIResponse O;S.SubmitRequest(Req(1),1.,O);TestEqual(TEXT("Replay"),S.SubmitRequest(Req(1),2.,O),EAetherAIResult::InvalidRequest);TestEqual(TEXT("Independent account"),S.SubmitRequest(Req(1,TEXT("other")),2.,O),EAetherAIResult::Accepted);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIRateLimitTest,"AgeOfAether.AI.RateLimit",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIRateLimitTest::RunTest(const FString&){auto P=MakeShared<FAetherAITestProvider>();FAetherAIService S;FAetherAIConfig C;C.MaxRequestsPerMinute=2;S.Initialize(C,P);FAetherAIResponse O;S.SubmitRequest(Req(1),1.,O);S.SubmitRequest(Req(2),2.,O);TestEqual(TEXT("Limited"),S.SubmitRequest(Req(3),3.,O),EAetherAIResult::RateLimited);TestEqual(TEXT("Expired"),S.SubmitRequest(Req(4),64.,O),EAetherAIResult::Accepted);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIContextTest,"AgeOfAether.AI.Context",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIContextTest::RunTest(const FString&){auto P=MakeShared<FAetherAITestProvider>();FAetherAIService S;FAetherAIConfig C;C.MaxContextCharacters=100;S.Initialize(C,P);auto R=Req(1);R.Context.PlayerInput=FString::ChrN(200,TCHAR('x'));FAetherAIResponse O;TestEqual(TEXT("Context"),S.SubmitRequest(R,1.,O),EAetherAIResult::ContextTooLarge);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIMemoryTest,"AgeOfAether.AI.Memory",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIMemoryTest::RunTest(const FString&){auto P=MakeShared<FAetherAITestProvider>();FAetherAIService S;FAetherAIConfig C;C.MaxMemoryEntries=2;S.Initialize(C,P);for(int32 I=0;I<3;++I){FAetherAIMemoryEntry E;E.Key=FString::Printf(TEXT("k%d"),I);E.Value=TEXT("v");TestTrue(TEXT("Memory"),S.AddMemory(TEXT("character"),E,I));}TArray<FAetherAIMemoryEntry>M;S.GetMemory(TEXT("character"),M);TestEqual(TEXT("Bounded"),M.Num(),2);TestEqual(TEXT("Evicted oldest"),M[0].Key,FString(TEXT("k1")));return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIOutputSafetyTest,"AgeOfAether.AI.OutputSafety",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIOutputSafetyTest::RunTest(const FString&){auto P=MakeShared<FAetherAITestProvider>();P->bReturnUnsafeOutput=true;FAetherAIService S;S.Initialize(FAetherAIConfig(),P);FAetherAIResponse O;TestEqual(TEXT("Unsafe"),S.SubmitRequest(Req(1),1.,O),EAetherAIResult::UnsafeOutput);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIToolSafetyTest,"AgeOfAether.AI.ToolSafety",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIToolSafetyTest::RunTest(const FString&){auto P=MakeShared<FAetherAITestProvider>();P->bReturnInvalidTool=true;FAetherAIService S;S.Initialize(FAetherAIConfig(),P);FAetherAIResponse O;TestEqual(TEXT("Tool rejected"),S.SubmitRequest(Req(1),1.,O),EAetherAIResult::InvalidToolProposal);return true;}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAetherAIProviderFailureTest,"AgeOfAether.AI.ProviderFailure",EAutomationTestFlags::ApplicationContextMask|EAutomationTestFlags::EngineFilter)
bool FAetherAIProviderFailureTest::RunTest(const FString&){auto P=MakeShared<FAetherAITestProvider>();P->bShouldSucceed=false;FAetherAIService S;S.Initialize(FAetherAIConfig(),P);FAetherAIResponse O;TestEqual(TEXT("Provider failure"),S.SubmitRequest(Req(1),1.,O),EAetherAIResult::ProviderRejected);return true;}
