#include "AI/AetherAIService.h"
bool FAetherAIService::Initialize(const FAetherAIConfig&C,TSharedPtr<IAetherAIProvider>P){if(!C.IsValid()||!P.IsValid())return false;Config=C;Provider=MoveTemp(P);Memories.Reset();RequestTimes.Reset();LastRequestIds.Reset();bRunning=true;return true;}
void FAetherAIService::Shutdown(){RequestTimes.Reset();LastRequestIds.Reset();Provider.Reset();bRunning=false;}
bool FAetherAIService::ValidateRequest(const FAetherAIRequest&R,FAetherAIResponse&O)const{if(!bRunning||!Config.bEnabled){O.Result=EAetherAIResult::ProviderUnavailable;return false;}if(R.RequestId==0||(LastRequestIds.Contains(R.Context.AccountId)&&R.RequestId<=LastRequestIds.FindRef(R.Context.AccountId))||R.Context.AccountId.TrimStartAndEnd().IsEmpty()||R.Context.CharacterId.TrimStartAndEnd().IsEmpty()||R.Context.PlayerInput.TrimStartAndEnd().IsEmpty()){O.Result=EAetherAIResult::InvalidRequest;return false;}if(R.Context.ApproximateCharacterCount()>Config.MaxContextCharacters){O.Result=EAetherAIResult::ContextTooLarge;return false;}return true;}
bool FAetherAIService::ConsumeRequestBudget(const FString&A,double N){TArray<double>&T=RequestTimes.FindOrAdd(A);T.RemoveAll([N](double X){return N-X>=60.;});if(T.Num()>=Config.MaxRequestsPerMinute)return false;T.Add(N);return true;}
bool FAetherAIService::ValidateOutput(FAetherAIResponse&R)const{if(R.Text.Len()>Config.MaxOutputCharacters)R.Text.LeftInline(Config.MaxOutputCharacters);if(R.Text.Contains(TEXT("BEGIN_SYSTEM_PROMPT"))||R.Text.Contains(TEXT("API_KEY="))||R.Text.Contains(TEXT("Authorization: Bearer"))){R.Text.Empty();R.ToolProposals.Reset();R.Result=EAetherAIResult::UnsafeOutput;return false;}if(!Config.bAllowToolProposals)R.ToolProposals.Reset();for(const auto&P:R.ToolProposals)if(P.Action==EAetherAIToolAction::None||P.TargetId.TrimStartAndEnd().IsEmpty()){R.Text.Empty();R.ToolProposals.Reset();R.Result=EAetherAIResult::InvalidToolProposal;return false;}return true;}
EAetherAIResult FAetherAIService::SubmitRequest(const FAetherAIRequest&R,double N,FAetherAIResponse&O){O=FAetherAIResponse();O.RequestId=R.RequestId;if(!ValidateRequest(R,O))return O.Result;if(!ConsumeRequestBudget(R.Context.AccountId,N)){O.Result=EAetherAIResult::RateLimited;return O.Result;}if(!Provider.IsValid()){O.Result=EAetherAIResult::ProviderUnavailable;return O.Result;}FAetherAIRequest E=R;TArray<FAetherAIMemoryEntry>M;if(GetMemory(R.Context.CharacterId,M))E.Context.Memory=MoveTemp(M);if(!Provider->Generate(E,Config,O)){O.Result=EAetherAIResult::ProviderRejected;return O.Result;}if(!ValidateOutput(O))return O.Result;O.Result=EAetherAIResult::Accepted;LastRequestIds.FindOrAdd(R.Context.AccountId)=R.RequestId;return O.Result;}
bool FAetherAIService::AddMemory(const FString&C,const FAetherAIMemoryEntry&E,double N){if(!bRunning||C.TrimStartAndEnd().IsEmpty()||E.Key.TrimStartAndEnd().IsEmpty()||E.Value.TrimStartAndEnd().IsEmpty())return false;TArray<FAetherAIMemoryEntry>&A=Memories.FindOrAdd(C);FAetherAIMemoryEntry X=E;X.CreatedAt=N;A.Add(X);while(A.Num()>Config.MaxMemoryEntries)A.RemoveAt(0);return true;}
bool FAetherAIService::GetMemory(const FString&C,TArray<FAetherAIMemoryEntry>&O)const{O.Reset();if(const TArray<FAetherAIMemoryEntry>*A=Memories.Find(C)){O=*A;return true;}return false;}
void FAetherAIService::ClearMemory(const FString&C){Memories.Remove(C);}
