#include "Characters/AetherClassEvolutionPresentationCatalog.h"
namespace { struct FCanonicalClass { const TCHAR* Id; const TCHAR* Path; const TCHAR* Evolutions[5]; };
const FCanonicalClass Classes[]={
 {TEXT("archer"),TEXT("Caminho da Precisão"),{TEXT("Batedor"),TEXT("Rastreador"),TEXT("Caçador Espectral"),TEXT("Atirador Fantasma"),TEXT("Olho de Deus / Juiz dos Ventos")}},
 {TEXT("warrior"),TEXT("Caminho da Fúria"),{TEXT("Recruta"),TEXT("Berserker"),TEXT("Campeão de Guerra"),TEXT("Lorde das Lâminas"),TEXT("Avatar da Guerra")}},
 {TEXT("mage"),TEXT("Caminho do Arcano"),{TEXT("Aprendiz"),TEXT("Feiticeiro Elemental"),TEXT("Arquimago"),TEXT("Tecelão do Éter"),TEXT("Senhor do Caos Primordial")}},
 {TEXT("tank"),TEXT("Caminho da Muralha"),{TEXT("Guardião"),TEXT("Fortaleza de Aço"),TEXT("Colosso"),TEXT("Bastião Imortal"),TEXT("Titã Ancestral")}},
 {TEXT("healer"),TEXT("Caminho da Luz"),{TEXT("Iniciado"),TEXT("Clérigo da Luz"),TEXT("Oráculo Sagrado"),TEXT("Serafim"),TEXT("Avatar da Vida Eterna")}}};}
UAetherClassEvolutionPresentationCatalog::UAetherClassEvolutionPresentationCatalog(){BuildCanonicalCatalog();}
void UAetherClassEvolutionPresentationCatalog::BuildCanonicalCatalog(){Entries.Reset();for(const FCanonicalClass& C:Classes){for(int32 I=0;I<5;++I){auto& E=Entries.AddDefaulted_GetRef();E.ClassID=FName(C.Id);E.EvolutionID=FName(FString::Printf(TEXT("%s.%02d"),C.Id,I+1));E.DisplayName=FText::FromString(C.Evolutions[I]);E.PathTitle=FText::FromString(C.Path);E.EvolutionStage=I+1;E.FallbackEvolutionID=FName(FString::Printf(TEXT("%s.01"),C.Id));}}}
const FAetherClassEvolutionPresentationDefinition* UAetherClassEvolutionPresentationCatalog::Find(FName ClassID,FName EvolutionID) const{const FString C=ClassID.ToString().ToLower(),E=EvolutionID.ToString().ToLower();for(const auto& X:Entries){if(X.ClassID.ToString().ToLower()==C&&X.EvolutionID.ToString().ToLower()==E)return &X;}return nullptr;}
const FAetherClassEvolutionPresentationDefinition* UAetherClassEvolutionPresentationCatalog::FindWithFallback(FName ClassID,FName EvolutionID) const{const auto* Exact=Find(ClassID,EvolutionID);if(!Exact)return Find(ClassID,FName(FString::Printf(TEXT("%s.01"),*ClassID.ToString())));if(Exact->VisualProfile||Exact->AnimationProfile||!Exact->Icon.IsNull()||!Exact->PresentationVFX.IsNull()||!Exact->PresentationSFX.IsNull())return Exact;return Find(ClassID,Exact->FallbackEvolutionID);}
bool UAetherClassEvolutionPresentationCatalog::ValidateCatalog(FString& OutError) const{OutError.Reset();if(Entries.Num()!=25){OutError=FString::Printf(TEXT("Expected 25 entries, got %d."),Entries.Num());return false;}TSet<FString> IDs;for(const auto& E:Entries){if(!E.IsIdentityValid()){OutError=TEXT("Invalid class/evolution identity.");return false;}FString K=E.ClassID.ToString().ToLower()+TEXT("|")+E.EvolutionID.ToString().ToLower();if(IDs.Contains(K)){OutError=FString::Printf(TEXT("Duplicate '%s'."),*K);return false;}IDs.Add(K);}return true;}